
source 'https://github.com/CocoaPods/Specs.git'
source 'http://repo.baichuan-ios.taobao.com/baichuanSDK/AliBCSpecs.git'

platform :ios, '9.0'
target 'BYNAPP' do
#网络请求数据
pod 'AFNetworking'
#上拉下拉刷新
pod 'MJRefresh'
#加载动画
pod 'MBProgressHUD'
#YYModel 等遍历框架
pod 'YYKit'
#图片处理 ，三级缓存
pod 'SDWebImage'
#空白界面框架
pod 'DZNEmptyDataSet'
#RACl
pod 'ReactiveObjC', '~> 3.1.0'
#自动轮滑
pod 'SDCycleScrollView'
#自动布局
pod 'SDAutoLayout', '~> 2.1.3'
#键盘控制
pod 'IQKeyboardManager'
#支付宝支付文档
pod 'AlipaySDK-iOS'
#控件布局
pod 'Masonry'

#pod 'FLAnimatedImage'

#友盟的依赖库
pod 'UMCCommon'
#pod 'UMCSecurityPlugins'
#友盟的推送
pod 'UMCPush'
#友盟的的分享
pod 'UMCShare/UI'
# 集成微信(精简版0.2M)
pod 'UMCShare/Social/ReducedWeChat'






end
